= PEGS method implementation 2025
:numbered:
:imagesdir: images


:BPS: <<BPS, Backup Power System>>
:LMS: <<LMS, Library Management System>>
:mib: <<mib, Intelligent Housing>>
:RSE: <<rse, Application de traitement des trajets RSE>>

== Teams

[%header,cols="2,3,1,1"]
|===
| Team 
| Subject
| Repo
| #1.0

| Johan Senac et Amadou Diallo 
| {BPS}
| https://github.com/FormalRequirements/re-2025-johan-amadou[GitHub]
| ☆☆☆☆☆
Pas de Release #1.0

| MURENGENZI Manzi et MUGISHA Igor 
| {LMS}
| https://github.com/FormalRequirements/re-2025-igor-et-godwin.git[GitHub]
| ★★☆☆☆
Bien mais manque le `README`

| Maya Smaili, Noémie Tandol et Kévin Véronési
| {RSE}
| https://github.com/Drosscend/re-2025-noemie-maya-kevin[GitHub hors Classrooom]
| ★★★★☆
Top mais manque le lien vers le PDF

| Honoris et Ikram
| {LMS}
| https://github.com/FormalRequirements/re-2025-the-honorable-iks[GitHub]
| ★★★☆☆
Minimum syndical

|  AL MUGHRABI Khaled, CAMUS Jonathan et DEFFAUGT Valentin
| {BPS}
| https://github.com/FormalRequirements/re-2025-khaled-jonathan-valentin[GitHub]
| ★★★★☆
Top, manque plus que la CI

| PEREZ OJEDA Jose, LANGELLIER Louis, SORIANO Raphael
| {mib}
| https://github.com/FormalRequirements/re-2025-jlr[GitHub] 
| ★★★☆☆
OK, mais manque les `.adoc` de base et la génération initiale de la doc.
Manque aussi un `README` dans la branche principale.

| Loic et Kado
| {BPS}
| https://github.com/FormalRequirements/re-2025-loic-kado[GitHub]
| ★★★☆☆
Minimum syndical  et attention à pointer dans le `README` sur vos releases

| Léo, Achille, et Othmane
| {LMS}
| https://github.com/FormalRequirements/re-2025-lao[GitHub]
| ★★★☆☆
Top le `README` mais manque la V1 du PDF lui-même (et la CI). 

| Marion DELATTRE et Dan-Gabriel VOVC
| {LMS}
| https://github.com/FormalRequirements/re-2025-dan-marion[GitHub]
| ★★★★☆
Très complet, me tarde de voir la génération de la doc
|===

== Case studies

[[BPS]]
=== Backup Power System (3 groups)

Initial description:

* A little context description (sorry for the French ;-):

**Thuy a passé 3 ans aux US (2003-2006) pour travailler sur le problème des défaillances de cause commune dans les systèmes de contrôle-commande de sûreté : 4 redondances, mais problème s'il y a le même bug de conception / logiciel dans les 4.
** Après une étude analytique et une analyse des retours d'expérience, une de conclusions est que les erreurs dans les exigences jouent un plus grand rôle que les erreurs de logiciel proprement dites.
** En plus, la défense en profondeur peut aussi être mise à mal si plusieurs lignes de défense d'appuient sur les mêmes exigences, ou si la même cause d'erreur affecte deux spécifications différentes.
** De retour en France en 2007, Thuy s'est donc attaché à améliorer la qualité des exigences de contrôle commande.
Il a pris un cas d'étude pas trop compliqué, mais pas trop simple non plus : le séquenceur des générateurs diesels (diesel generators load sequencer, ou DGLS).
** Grosso modo, il faut détecter les conditions où le DGLS doit agir, manipuler un certains nombre de disjonteurs, démarrer le générateur, attendre qu'il soit prêt, puis par intervalles de 5 secondes, relester les équipements alimentés par le générateur.
** Les exigences du DGLS sont exprimées dans un diagramme fonctionnel (en équivalent de SCADE) déterministe, mais c'est comme de la programmation.
** Comment s'assurer que le diagramme fonctionnel est correct ?
Pour cela, Thuy s'est penché sur le BPS, le système physique dont le DGLS est le contrôle commande.
** Au plus haut niveau, les exigences du BPS sont très simples.
** Puis les choses se compliquent petit à petit quand on introduit les redondances et la possibilité de maintenance en fonctionnement et la nécessité de faire des tests périodiques.
** Elles se compliquent encore quand on établit l'architecture du division (redodance) du BPS : capteurs de tension et de fréquence électriques, disjoncteurs, générateur diesel, système de contrôle-commande (le DGLS).
** Bien sûr, il faut aussi modéliser l'environnement du BPS : le MPS (alimentation électrique principale), l'opérateur humain, et les "clients" que le BPS doit réalimenter.
** En faisant tout cela, on replace le DGLS dans son contexte opérationnel, et par simulation, on peut vérifier que les exigences sont OK pour toutes les situations envisagées.

- Thuy Nguyen slides (https://docs.google.com/presentation/d/1t4lkNHn87pgG1l_maRUyfH3Yvxp6-f2C/edit?usp=drive_link&ouid=109827482140790497874&rtpof=true&sd=true[PPTX])


[[LMS]]
=== Library Management System (4 groups)

Initial descriptions :

- https://github.com/ddd-by-examples/library?ref=hackernoon.com#domain-description 
- https://www.naukri.com/code360/library/design-a-library-management-system-low-level-design 

[[mib]]
=== Maison Intelligente

Lien sur un descriptif de la MIB de Blagnac : chapitre  3 de https://jmbruel.github.io/sysmlpapyrusbook/PapyrusSysMLinAction.pdf[ce document].

[[rse]]
=== Application de traitement des trajets RSE

...

== Expected outcomes

[%interactive]
* [ ] (MUST) A GitHub implementation of the PEGS approach applied to the chosen Case study
* [ ] (MUST) Description of the team (members, roles)
* [ ] (SHOULD) The requirements document following the standard plan
* [ ] (COULD) If possible, the previous requirements document is generated from the repo content (CI/CD ?)

(This list uses the MoSCoW classification criteria.)

== Evaluation criteria 

[%header,cols="2,1,6"]
|===
Criteria    | Weight    | Expectations

| 📚 PEGS fidelity | 50% | Respects PEGS plans, rules and principles 
| ✅ Correctness | 20% | The requirements are sound and match the case study 
| 🔎 Readibility | 10% | PEGS book and Github repo are easy to read and navigate 
| ⚙️ Genericity | 10% | How generic is the GitHub (could be added in the free materials on https://requirements.university) 
| 🤖 PEGS implementation | 10% | Key artefacts (requirements' kinds, validation rules, standard plans) are implemented so that they are possibily used in some CI/CD process in the future 
|===
